"""Render the *real* skyplothelper globes that the #11 globe-motion manim demos
cross-fade into (demos C "the Euler trio" and D "spin, nutation & precession";
see ``.claude/MANIM_DEMO_BRIEFS.md`` §C/§D and §4).

This is the sph side only — it draws no animation, just the genuine posed-globe
PNGs the manim scenes dissolve their schematic 3-D geometry into. The division of
labor is the whole point: skyplothelper is the source of scientific truth (a real
``make_planet_frame`` posed by ``euler_to_fits_ortho``, a real ``add_pole_rod``),
manim is only the camera and typographer.

All on the shared navy sky canvas so the cross-fades are seamless:

* ``assets/globe_euler_posed.png`` — a real Blue-Marble globe posed at the exact
  Euler triple the trio scene sweeps to (``rotation, obliquity, perspective`` =
  ``EULER_TRIPLE``). Carries the same gold-equator / green-prime-meridian
  highlights the manim wireframe uses; since the scene poses that wireframe from
  these very sph params, the dissolve lands frame-for-frame.
* ``assets/globe_precession.png`` — a Black-Marble look-down globe with a real
  ``add_pole_rod`` spin axis, matching #17 §4's matplotlib precession figure, for
  the motion demo's payoff cut.
* ``assets/euler_recap_NN.jpg`` / ``assets/precess_recap_NN.jpg`` — short strips of
  real draped globes each demo flips through after its cut, so the *actual* sph
  globe is seen performing the motions rather than only posing. The precession
  strip is generated by ``make_globe_angles`` (one clean spin, one nutation wobble
  and one full precession via its whole-animation totals).

Run in the astropy env (``cenv``), from the repo root::

    python docs/manim/make_globe_motions_assets.py
"""
from __future__ import annotations

import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

import skyplothelper as sph

# The manim scenes render on this navy (see the brief); the sph PNGs must share it
# so the dissolve has no visible seam.
SKY = "#16203A"
GRID = "#4E6188"          # faint graticule, matching the manim wireframe
EQ_C = "#C29B3C"          # gold equator  (uranometria)
PM_C = "#5E8C7E"          # green prime meridian (uranometria)
ROD_C = "#E8DDB5"         # wheat pole rod, as in the notebook capstone

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "..", "examples", "data")
ASSETS = os.path.join(HERE, "assets")

BLUE_MARBLE = os.path.join(DATA, "world.topo.bathy.200412.3x5400x2700.jpg")
BLACK_MARBLE = os.path.join(DATA, "BlackMarble_2016_01deg.jpg")

# The Euler trio the demo C scene animates, in the same order the arcs sweep. The
# perspective endpoint (60) is where the precession beat lands — the scene poses its
# wireframe from these exact sph params, so this cut matches it frame-for-frame.
EULER_TRIPLE = (45.0, 30.0, 60.0)      # rotation, obliquity, perspective
# Demo D cuts to a real tilted globe + spin axis. The tilt is kept moderate (near
# the wireframe's 26° obliquity) on purpose: the recap sweeps precession by
# re-centering the frame on the sub-observer, which swings the visible face by
# ±tilt — a steep look-down (60°) flips clear past the south pole and reads as a
# tumble, not the wireframe's gentle cone. 30° keeps precession a gentle lean and
# matches the schematic's tilt, so the dissolve into this cut lines up too.
PRECESS_TRIPLE = (30.0, 30.0, 0.0)


def _drape(ax, path):
    """Reproject an equirectangular raster onto the globe frame's pixel grid, below
    the graticule (the notebook's drape() helper)."""
    hdu = sph.pseudofits_from_image(path, geo=True)
    out_hdr = ax.wcs.to_header()
    nx = round(ax.get_xlim()[1] - ax.get_xlim()[0])
    ny = round(ax.get_ylim()[1] - ax.get_ylim()[0])
    out_hdr["NAXIS1"], out_hdr["NAXIS2"] = nx, ny
    bg = np.nan_to_num(sph.reproject_rgb_map(hdu, out_hdr, shape_out=(ny, nx)))
    return ax.imshow(bg, zorder=-10)


def _highlight_lines(ax):
    """Gold equator + green prime meridian — the two curves the manim wireframe
    also draws, so the dissolve has anchors that line up."""
    t = np.linspace(-90, 90, 60)
    sph.plot_line_globe(ax, t, np.zeros_like(t), color=EQ_C, lw=2.4, densify=False,
                        zorder=6)
    sph.plot_line_globe(ax, np.zeros_like(t), t, color=PM_C, lw=2.4, densify=False,
                        zorder=6)


def render_euler_posed():
    """A real Blue-Marble globe posed at the exact trio the scene animates."""
    clon, clat, pole = sph.euler_to_fits_ortho(*EULER_TRIPLE)
    fig = plt.figure(figsize=(5.2, 5.2), facecolor=SKY)
    ax = sph.make_planet_frame(111, body="earth", center_LONdeg=clon,
                               center_LATdeg=clat, lonpole=pole, Naxispix=700,
                               grid=False)
    _drape(ax, BLUE_MARBLE)
    sph.plot_ortho_grid(ax, front_color=GRID, front_lw=0.7, show_back=False)
    _highlight_lines(ax)
    out = os.path.join(ASSETS, "globe_euler_posed.png")
    fig.savefig(out, dpi=150, facecolor=SKY, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)
    print("wrote", out, f"(center={clon:.1f},{clat:.1f} lonpole={pole:.1f})")


def render_precession_globe():
    """A real Black-Marble look-down globe with a spin-axis pole rod — the #17 §4
    companion the motion demo cuts to."""
    clon, clat, pole = sph.euler_to_fits_ortho(*PRECESS_TRIPLE)
    fig = plt.figure(figsize=(5.2, 5.2), facecolor=SKY)
    ax = sph.make_planet_frame(111, body="earth", center_LONdeg=clon,
                               center_LATdeg=clat, lonpole=pole, Naxispix=700,
                               grid=False)
    _drape(ax, BLACK_MARBLE)
    sph.plot_ortho_grid(ax, front_color=GRID, front_lw=0.7, show_back=False)
    sph.add_pole_rod(ax, color=ROD_C, stroke_color="0.05", length=1.55)
    out = os.path.join(ASSETS, "globe_precession.png")
    fig.savefig(out, dpi=150, facecolor=SKY, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)
    print("wrote", out, f"(center={clon:.1f},{clat:.1f} lonpole={pole:.1f})")


def _recap_frames(prefix, params, raster, rod=False, size_px=560):
    """Render a short strip of real draped globes for a demo's closing 'recap' —
    the scene flips through these so the *actual* sph globe is seen performing the
    motions, not just posing. ``params`` are ``(center_lon, center_lat, lonpole)``
    triples. Written as JPEGs at display size: a photographic globe is ~40 kB that
    way versus ~500 kB as PNG, which keeps a ~25-frame strip smaller than the video
    it rides in."""
    hdu_path = raster
    for i, (clon, clat, pole) in enumerate(params):
        fig = plt.figure(figsize=(4.6, 4.6), facecolor=SKY)
        ax = sph.make_planet_frame(111, body="earth", center_LONdeg=clon,
                                   center_LATdeg=clat, lonpole=pole, Naxispix=420,
                                   grid=False)
        _drape(ax, hdu_path)
        sph.plot_ortho_grid(ax, front_color=GRID, front_lw=0.7, show_back=False)
        if rod:
            sph.add_pole_rod(ax, color=ROD_C, stroke_color="0.05", length=1.55)
        else:
            _highlight_lines(ax)
        out = os.path.join(ASSETS, f"{prefix}_{i:02d}.jpg")
        fig.savefig(out, dpi=size_px / 4.6, facecolor=SKY, bbox_inches="tight",
                    pad_inches=0.05, pil_kwargs={"quality": 82})
        plt.close(fig)
    print(f"wrote {len(params)} {prefix}_NN.jpg recap frames")


def euler_recap_params(n_per=8):
    """A short tour of the three motions, starting from the Euler cut's pose so the
    strip continues it seamlessly: spin, then a nod of obliquity, then precession."""
    r0, o0, p0 = EULER_TRIPLE
    triples = []
    for t in np.linspace(0, 1, n_per, endpoint=False):
        triples.append((r0 + 40 * t, o0, p0))                   # spin
    for t in np.linspace(0, 1, n_per, endpoint=False):
        triples.append((r0 + 40, o0 + 15 * t, p0))              # nutation-style nod
    for t in np.linspace(0, 1, n_per + 1):
        triples.append((r0 + 40, o0 + 15, p0 + 40 * t))         # precession
    return [sph.euler_to_fits_ortho(*t) for t in triples]


def precess_recap_params(n_per=12):
    """The three motions *in turn* on the real globe — a partial spin, a nutation
    nod, then a partial precession — so the draped recap showcases the same isolated
    sweeps the wireframe does (one combined cycle reads as muddled; isolated reads
    cleanly, as ``euler_recap_params`` does for demo C). Sweeps are kept *partial* on
    purpose: a full 360 in a dozen frames strobes, whereas ~80-100 over the same
    frames is a smooth ~7 deg/frame that still plainly shows each motion. Each
    ``make_globe_angles`` call drives one whole-animation total, the others zero.
    ``make_planet_frame`` re-centers on the sub-observer, so precession swings the
    face by +/-tilt — the moderate PRECESS_TRIPLE tilt keeps it a gentle lean."""
    start = [0.0, PRECESS_TRIPLE[1], 0.0]
    parts = []
    lo, la, po = sph.make_globe_angles(start, n_steps=n_per,
                                       spin_total=85.0, prec_total=0.0)
    parts += list(zip(lo, la, po))                          # a partial spin
    lo, la, po = sph.make_globe_angles(start, n_steps=n_per, spin_total=0.0,
                                       nut_cycles=1, nut_amp=8.0, prec_total=0.0)
    parts += list(zip(lo, la, po))                          # a nutation nod
    lo, la, po = sph.make_globe_angles(start, n_steps=n_per + 1,
                                       spin_total=0.0, prec_total=105.0)
    parts += list(zip(lo, la, po))                          # a precession lean
    return parts


if __name__ == "__main__":
    os.makedirs(ASSETS, exist_ok=True)
    render_euler_posed()
    render_precession_globe()
    _recap_frames("euler_recap", euler_recap_params(), BLUE_MARBLE)
    _recap_frames("precess_recap", precess_recap_params(), BLACK_MARBLE, rod=True)
