"""Bundled custom colormaps for astronomical imaging.

A small curated set of image colormaps, registered with
matplotlib under the ``sph.`` prefix (à la cmocean's ``cmo.`` / cmasher's
``cmr.``) so they work anywhere a colormap name is accepted::

    ax.imshow(data, cmap='sph.deepsky')
    quicklook_fits('img.fits', cmap='sph.lagoon')

Each map also gets a reversed ``sph.<name>_r`` variant. Use
:func:`list_colormaps` to see them, :func:`get_colormap` to fetch one, and
:func:`show_colormaps` for a swatch preview. Each map is also reachable as a
module attribute (matplotlib/cmocean-style), including its ``_r`` reverse::

    from skyplothelper import colormaps
    ax.imshow(data, cmap=colormaps.deepsky)
    ax.imshow(data, cmap=colormaps.diff_tealorange_r)

The color data lives in the auto-generated ``_colormaps_lut.py``:

* ``LUTS``    — 256-point lookup tables for the luminance-smoothed maps
  (their smoothing can't be reduced to a few anchors).
* ``ANCHORS`` — exact ``{nodes, colors}`` control points for the plain
  diverging maps, reconstructed losslessly with ``from_list``.

That data is generated by an internal baking script; none of the
colormap-building tooling is bundled here.
"""

from __future__ import annotations

from typing import Any, cast

import matplotlib as mpl
from matplotlib.colors import Colormap, LinearSegmentedColormap

from ._colormaps_lut import ANCHORS as _ANCHORS
from ._colormaps_lut import LUTS as _LUTS

# The generated data module has no annotations; give the consumers concrete
# (permissive) types so the mixed-value ANCHORS entries type-check cleanly.
LUTS: dict[str, list[list[float]]] = _LUTS
ANCHORS: dict[str, dict[str, Any]] = cast("dict[str, dict[str, Any]]", _ANCHORS)

# Prefix for the matplotlib registry — namespaced to avoid colliding with (or
# being shadowed by) matplotlib's or another package's colormap names.
PREFIX = "sph."


def _build() -> dict[str, Colormap]:
    """Reconstruct every bundled colormap keyed by its bare name."""
    cmaps: dict[str, Colormap] = {}
    # LUT maps: evenly-spaced 256-point tables.
    for name, rows in LUTS.items():
        cmaps[name] = LinearSegmentedColormap.from_list(
            PREFIX + name, [list(r) for r in rows], N=len(rows))
    # Anchor maps: exact control points at (possibly non-uniform) positions.
    for name, spec in ANCHORS.items():
        pairs = [(float(x), list(c))
                 for x, c in zip(spec["nodes"], spec["colors"])]
        cmaps[name] = LinearSegmentedColormap.from_list(PREFIX + name, pairs, N=256)
    return cmaps


# Bare-name -> Colormap (its .name is the prefixed form). Insertion order
# follows the curated order in _colormaps_lut.py (LUTs, then diffs).
_CMAPS: dict[str, Colormap] = _build()


def _register() -> None:
    """Register each colormap (and its ``_r`` reverse) with matplotlib.

    Idempotent: skips names already present, so re-importing the package
    doesn't raise on the second registration.
    """
    for name, cmap in _CMAPS.items():
        forward = PREFIX + name
        reverse = forward + "_r"
        if forward not in mpl.colormaps:
            mpl.colormaps.register(cmap, name=forward)
        if reverse not in mpl.colormaps:
            mpl.colormaps.register(cmap.reversed(), name=reverse)


_register()


def list_colormaps(include_reverse: bool = False) -> list[str]:
    """Return the registered bundled colormap names (prefixed with ``sph.``).

    Parameters
    ----------
    include_reverse : bool
        Also include the reversed ``sph.<name>_r`` variants (interleaved
        after each forward map). Default ``False``.

    Returns
    -------
    list of str
        Names in the curated bundle order, e.g. ``['sph.deepsky', ...]``.
    """
    if include_reverse:
        out: list[str] = []
        for name in _CMAPS:
            out.append(PREFIX + name)
            out.append(PREFIX + name + "_r")
        return out
    return [PREFIX + name for name in _CMAPS]


def get_colormap(name: str) -> Colormap:
    """Fetch a bundled colormap by name.

    Accepts the bare name (``'deepsky'``), the prefixed name
    (``'sph.deepsky'``), or a reversed variant (``'sph.deepsky_r'``).

    Returns
    -------
    matplotlib.colors.Colormap
    """
    reg = name if name.startswith(PREFIX) else PREFIX + name
    # Prefer the matplotlib registry (so a user override of the registered map
    # wins), but fall back to the registration-independent ``_CMAPS`` table —
    # built directly from the bundled LUT data at import — so a bundled map
    # still resolves even if registration was somehow skipped or its registry
    # entry was removed. This keeps ``get_colormap`` / ``colormaps.<name>``
    # working (and returning a real Colormap object) regardless of registry
    # state.
    if reg in mpl.colormaps:
        return mpl.colormaps[reg]
    bare = reg[len(PREFIX):]
    if bare.endswith("_r") and bare[:-2] in _CMAPS:
        return _CMAPS[bare[:-2]].reversed()
    if bare in _CMAPS:
        return _CMAPS[bare]
    raise KeyError(name)


def show_colormaps(names: list[str] | None = None, *, width: float = 6.0) -> Any:
    """Preview bundled colormaps as horizontal gradient swatches.

    Parameters
    ----------
    names : list of str, optional
        Which colormaps to show (bare or prefixed names). Default: all
        forward maps in bundle order.
    width : float
        Figure width in inches.

    Returns
    -------
    matplotlib.figure.Figure
    """
    import matplotlib.pyplot as plt
    import numpy as np

    names = names or list_colormaps()
    gradient = np.linspace(0, 1, 256).reshape(1, -1)
    fig, axes = plt.subplots(len(names), 1,
                             figsize=(width, 0.35 * len(names) + 0.3))
    ax_list = list(axes.ravel()) if isinstance(axes, np.ndarray) else [axes]
    for ax, nm in zip(ax_list, names):
        ax.imshow(gradient, aspect="auto", cmap=get_colormap(nm))
        ax.set_axis_off()
        ax.text(-0.01, 0.5, nm, va="center", ha="right",
                transform=ax.transAxes, fontsize=9, family="monospace")
    fig.subplots_adjust(left=0.26, right=0.99, top=0.99, bottom=0.01, hspace=0.3)
    return fig


def __getattr__(name: str) -> Colormap:
    """Expose bundled colormaps as module attributes (``colormaps.deepsky``).

    Mirrors matplotlib/cmocean-style access. Accepts a bare bundled name or
    its ``_r`` reverse; any other attribute raises AttributeError (so normal
    module lookup semantics are preserved).
    """
    try:
        return get_colormap(name)
    except KeyError as exc:
        raise AttributeError(
            f"module {__name__!r} has no colormap or attribute {name!r}") from exc


def __dir__() -> list[str]:
    """List real module members + bundled colormap names for tab-completion."""
    names = [n for n in _CMAPS] + [n + "_r" for n in _CMAPS]
    return sorted(set(globals()) | set(names))


__all__ = ["list_colormaps", "get_colormap", "show_colormaps", "PREFIX"]
